variables:
  IMAGE_NAME: ahmeddwieb/crm-product-mangament
  IMAGE_TAG: java-app-1.0

stages:
  - build
  - deploy

build-image:
  stage: build
  image: docker:28.4.0-cli
  services:
    - name: docker:28.4.0-dind
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  image: node:18
  before_script:
    - npm install -g @railway/cli
  script:
    - echo "Token exists? ${RAILWAY_TOKEN:+yes}"
    - railway up --service CRM-Product-Mangament --ci
  only:
    - master
