variables:
  IMAGE_NAME: ahmeddwieb/crm-product-mangament
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA  # كل build له tag مميز حسب commit
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

build-image:
  stage: build
  image: docker:28.4.0-cli
  services:
    - name: docker:28.4.0-dind
      alias: docker
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  script:
    - docker build --pull --cache-from $IMAGE_NAME:latest -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:latest

  only:
    - master


deploy:
  stage: deploy
  image: node:18
  before_script:
    - npm install -g @railway/cli
  script:
    - echo "Checking Railway token... ${RAILWAY_TOKEN:+found}"
    - railway up --service CRM-Product-Mangament --ci
  only:
    - master
