version: '3.8'

services:
  crm-app:
    image: ahmeddwieb/crm-product-mangament:latest
    container_name: crm-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped

volumes:
  mongo_data:
